save_dir: "flappy_results"
label_types: ["corrections","demo-action-mismatch","demo-acceptable","random-action-mismatch","random-acceptable"]
num_runs: 50
sourceQ_file: "../inputfiles/flappy/source/Q.csv"
targetQ_file: "../inputfiles/flappy/target/Q.csv"
target_env: "TargetFlappyBird-v0"
percentile: 0.7
budget_list: "range(250, 7600, 250)"
percent_data: 0.8
state_visits: "../inputfiles/flappy/sim_on_real/state_counts.csv"